name: Hexo Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Setup env
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GITALK_SECRET: ${{ secrets.GITALK_SECRET }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY"> ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "Github Actions"
          git config --global init.defaultBranch "main"
          git config --global user.email "cli@github.com"
                
      - name: hexo build and compress images
        run: |
          sudo apt update && sudo apt install jpegoptim -y
          git clone --depth=1 https://github.com/Hexrotor/blogsrc

          cd blogsrc
          sed -i "s@SECRET_TO_BE_REPLACE@$GITALK_SECRET@g" _config.redefine.yml
          cp -ruf post_imgs/* node_modules/hexo-theme-redefine/source/images/post_imgs
          
          # replace images links with jsdelivr cdn
          cat replace.sh|bash

          chmod 755 ./node_modules/.bin/hexo
          ./node_modules/.bin/hexo clean
          ./node_modules/.bin/hexo g
          find ./public/images/post_imgs/ -not -iname "*_raw.jpg" -not -iname "*_raw.jpeg" -iname "*.jpg" -o -iname "*.jpeg" | xargs jpegoptim -m 80
          ./node_modules/.bin/hexo d
